version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      runtime-dependencies:
        patterns:
          - "cryptography"
          - "typing-extensions"
      dev-dependencies:
        patterns:
          - "pytest*"
          - "hypothesis"
          - "ruff"
          - "mypy"
          - "tox"
      docs-dependencies:
        patterns:
          - "mkdocs*"
          - "pymdown-extensions"
          - "pygments"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
