sonar.projectKey=Di3Z1E_spindlex
sonar.organization=di3z1e
sonar.host.url=https://sonarcloud.io

# Path to sources
sonar.sources=spindlex
sonar.tests=tests
sonar.python.version=3.13

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Coverage report
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml
