name: Release

on:
  release:
    types: [published]

jobs:
  compatibility-matrix:
    name: Release compatibility matrix
    uses: ./.github/workflows/ci-matrix.yml
    secrets: inherit

  integration:
    name: Release integration
    uses: ./.github/workflows/integration.yml
    secrets: inherit

  pypi-publish:
    name: Upload release to PyPI
    needs:
      - compatibility-matrix
      - integration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build
        run: |
          uv pip install --system build
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
