name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  compatibility-matrix:
    name: Release compatibility matrix
    uses: ./.github/workflows/ci-matrix.yml
    secrets: inherit

  integration:
    name: Release integration
    uses: ./.github/workflows/integration.yml
    secrets: inherit

  pypi-publish:
    name: Upload release to PyPI
    needs:
      - compatibility-matrix
      - integration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.11'
      - name: Build
        run: |
          uv pip install --system build
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
