name: Traffic to Badge

on:
  schedule:
    - cron: '0 0 * * *'     # every day at midnight UTC
  workflow_dispatch:        # allows manual trigger

jobs:
  traffic:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Traffic Badges
        uses: yi-Xu-0100/traffic-to-badge@v1.4.0
        id: traffic
        with:
          my_token: ${{ secrets.TRAFFIC_TOKEN }}
          traffic_branch: traffic
          views_color: brightgreen
          clones_color: brightgreen
          total_views_color: brightgreen
          total_clones_color: brightgreen

      - name: Deploy traffic data
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ steps.traffic.outputs.traffic_branch }}
          publish_dir: ${{ steps.traffic.outputs.traffic_path }}
